{% set name = "include-what-you-use" %}
{% set version = "0.18" %}
{% set llvm_version = "14.*" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 497b8d01e7faf561a20b09fdff38b66ba50febe4b4b7cf3cf2e809ee3be55a99

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - python
    - make
  host:
    - clangdev {{ llvm_version }}
    - llvmdev {{ llvm_version }}
    - llvm {{ llvm_version }}
    - libclang-cpp {{ llvm_version }}
    - lld {{ llvm_version }}
test:
  commands:
    - {{ name }} --version
    - {{ name }} --help

about:
  home: https://include-what-you-use.org
  summary: 'A tool for use with clang to analyze #includes in C and C++ source files'
  description: |
    "Include what you use" means this: for every symbol (type, function, variable, or macro)
    that you use in foo.cc (or foo.cpp), either foo.cc or foo.h should include a .h file that
    exports the declaration of that symbol. (Similarly, for foo_test.cc, either foo_test.cc or foo.h
    should do the including.) Obviously symbols defined in foo.cc itself are excluded from this requirement.
  license: NCSA  # University of Illinois/NCSA Open Source
  license_family: OTHER  # NCSA
  license_file: LICENSE.TXT
  doc_url: https://include-what-you-use.org
  dev_url: https://github.com/include-what-you-use/include-what-you-use

extra:
  recipe-maintainers:
    - xmnlab
